import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next.js Cleeng PoC",
  description: "Generated by create next app",
};

const PaymentProvider = dynamic(() => import("@/provider"), { ssr: false });

export default function PaymentLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PaymentProvider>{children}</PaymentProvider>
      </body>
    </html>
  );
}
